#page title
page_title                                :                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1523968394                        # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                   # Enter Google Play Store URL.
presskit_download_link                    :                                   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get more things done, every day.

enable_smart_app_banner                   : true                              # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Michael Tigas                                
your_link                                 : https://twitter.com/michael_tigas
your_city                                 : Melbourne, Australia. 🇦🇺 🦘
email_address                             : focusedworkapp@michaeltigas.com.au
facebook_username                         : FocusedWorkApp                                          
instagram_username                        : focusedworkapp
twitter_username                          : FocusedWorkApp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create timed Focus Sessions.
    description                           : Design the perfect structure for getting work done, to stay fresh and productive.
    fontawesome_icon_name                 : stopwatch
    
  - title                                 : Adjustable daily goals.
    description                           : Build momentum and a streak, by completing focused work every day.
    fontawesome_icon_name                 : chart-pie

  - title                                 : Distraction alerts.
    description                           : Be reminded to stay focused, and when to take a break.
    fontawesome_icon_name                 : exclamation

  - title                                 : iCloud Syncing.
    description                           : Freely move between your iPhone and iPad, depending on your task. (macOS coming soon!)
    fontawesome_icon_name                 : sync

  - title                                 : Share productivity time with Toggl.
    description                           : Track time once, by assigning projects and tags to your focus sessions.
    fontawesome_icon_name                 : power-off

  - title                                 : Dark Mode.
    description                           : Perfect for productive night owls, so the timer doesn't light up your room.
    fontawesome_icon_name                 : moon

  - title                                 : App Icons.
    description                           : Twelve colours, with Light + Dark variants for matching your home screen.
    fontawesome_icon_name                 : images

  - title                                 : Widgets.
    description                           : Focus session timers, quickly start a session, view today's productivity goals.
    fontawesome_icon_name                 : th-large



# Press Review List                       Edit, add or remove press reviews to be presented.
pressreviews                              :

  - author                                : Ryan Christoffel
    quote                                 : A simple, but valuable utility for creating timed focus sessions of productivity.
    sitename                              : MacStories
    siteurl                               : https://www.macstories.net/reviews/focused-work-review-staying-on-task-amidst-growing-distractions/
    fontawesome_icon_name                 : newspaper
    
  - author                                : Victor Marks
    quote                                 : Focused Work is a tool that helps overcome that first step.
    sitename                              : Knapsack
    siteurl                               : https://knapsack.news/2020/09/09/focused-work-how-do-we-get-anything-done-at-all/
    fontawesome_icon_name                 : newspaper
    
  - author                                : Oliver Haslam
    quote                                 : Focused Work helps you stay on track better than ever.
    sitename                              : iMore
    siteurl                               : https://www.imore.com/focused-work-gains-ios-14-home-screen-widgets-help-you-stay-track-better-ever/
    fontawesome_icon_name                 : newspaper



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/focusedwork_coverimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#4c69af"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown