#page title
page_title                                : Focused Work    # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://forms.gle/5d9oopQpLitn4PP6A       # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://focusedwork.app/presskit          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Focused Work                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get more things done, in less time.

enable_smart_app_banner                   : false                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Michael Tigas                                
your_link                                 : https://heyimakeapps.com
your_city                                 : Melbourne 🇦🇺 🦘
email_address                             : focusedworkapp@michaeltigas.com.au
facebook_username                         : FocusedWorkApp                                          
instagram_username                        : focusedworkapp
twitter_username                          : FocusedWorkApp
github_username                           : teeeeeegz
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Avoid burnout. Find your flow state.
    description                           : Create timed Focus Session's for common tasks, with structured Planning, Focused Work, and Break stages.
    fontawesome_icon_name                 : stopwatch
    
  - title                                 : Create a sustainable productivity habit.
    description                           : Adjustable daily goals help you build momentum by completing focused work each day.
    fontawesome_icon_name                 : chart-pie

  - title                                 : Stay Focused alerts.
    description                           : Your pocket study-buddy reminds you to stay on track, and lets you know when it's time to take a break.
    fontawesome_icon_name                 : exclamation

  - title                                 : Switch devices, based on the agenda.
    description                           : Everything is synced with iCloud, so you can freely move between your iPhone and iPad for the next Focus Session (and macOS soon!).
    fontawesome_icon_name                 : sync

  - title                                 : Send your Focused Work to Toggl.
    description                           : Only track your time once by assigning a Toggl project to your Focus Session, to auto-submit completed Focused Work stages.
    fontawesome_icon_name                 : power-off

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown